[project]
name = "llm-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-mistralai>=1.0.1",
    "langchain-openai>=1.0.2",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.11.0",
]
